# -*- coding: utf-8 -*-
"""Generate fonts.css.

The Segoe faces were recovered from the PDF, so each one is a *subset*: its cmap
still maps every codepoint, but glyphs the original pages never used are blank.
Chrome therefore never falls through to another cut - it happily paints nothing.
The fix is to declare each face's real coverage with unicode-range, so a
character a subset lacks is handed to the next cut in the stack.
"""
import glob
import io
import os

import fitz

EXTRA = (u'—–‘’“”→←§≠×≤≥'
         u'★·•… ′°±≈⇒✓✗'
         u'₁ₑₘᶜₑ')
CHARS = u''.join(chr(c) for c in range(0x20, 0x7f)) + EXTRA

ALIAS = {
    'CAAAAA_SegoeUI.ttf': 'SegReg',
    'DAAAAA_SegoeUI-Bold.ttf': 'SegBoldD',
    'EAAAAA_SegoeUI-Bold.ttf': 'SegBoldE',
    'GAAAAA_SegoeUI-Bold.ttf': 'SegBoldG',
    'JAAAAA_SegoeUI-Bold.ttf': 'SegBoldJ',
    'HAAAAA_SegoeUI-Bold.ttf': 'SegBoldH',
    'IAAAAA_SegoeUI-Italic.ttf': 'SegItal',
    'TAAAAA_SegoeUI-BoldItalic.ttf': 'SegBoldItal',
    'AAAAAA_SegoeUI-Semibold.ttf': 'SegSemiA',
    'KAAAAA_SegoeUI-Semibold.ttf': 'SegSemiK',
    'XAAAAA_SegoeUI-SemiboldItalic.ttf': 'SegSemiItal',
    'BAAAAA_SegoeUIBlack.ttf': 'SegBlack',
    'QAAAAA_SegoeUISymbol.ttf': 'SegSym',
    # Selawik is Microsoft's metric-compatible open clone of Segoe UI: identical
    # advances, complete Latin coverage. It backs every recovered subset.
    'selawk.ttf': 'SelReg',
    'selawkb.ttf': 'SelBold',
    'selawksb.ttf': 'SelSemi',
}


def inked(path, fo, ch):
    """True only if the face paints actual ink for `ch`.

    A cmap hit is not enough: these subsets keep the full cmap but stripped the
    outlines of glyphs the original pages never used, so Chrome paints nothing
    and never falls through. Render the character and look for pixels.
    """
    if ch == ' ':
        return True
    if not fo.has_glyph(ord(ch)):
        return False
    doc = fitz.open()
    page = doc.new_page(width=40, height=40)
    tw = fitz.TextWriter(page.rect)
    try:
        tw.append((6, 30), ch, font=fo, fontsize=24)
    except Exception:
        doc.close()
        return False
    tw.write_text(page)
    pix = page.get_pixmap(colorspace=fitz.csGRAY)
    dark = any(b < 200 for b in pix.samples)
    doc.close()
    return dark


def ranges(cps):
    cps = sorted(cps)
    out, i = [], 0
    while i < len(cps):
        j = i
        while j + 1 < len(cps) and cps[j + 1] == cps[j] + 1:
            j += 1
        out.append('U+%04X' % cps[i] if i == j else 'U+%04X-%04X' % (cps[i], cps[j]))
        i = j + 1
    return ','.join(out)


faces = []
for path in sorted(glob.glob('fonts/*.ttf')):
    name = os.path.basename(path)
    alias = ALIAS.get(name)
    if not alias:
        continue
    fo = fitz.Font(fontfile=path)
    cps = [ord(c) for c in CHARS if inked(path, fo, c)]
    if not cps:
        continue
    faces.append((alias, name, cps))

css = [u'/* generated by mkfonts.py - real coverage of every recovered subset */']
for alias, name, cps in faces:
    css.append(u'@font-face{font-family:%s;src:url(fonts/%s) format("truetype");'
               u'unicode-range:%s}' % (alias, name, ranges(cps)))
# synthesised oblique of the full regular cut, for italic characters the true
# italic subset never carried
css.append(u'@font-face{font-family:SegObl;src:url(fonts/CAAAAA_SegoeUI.ttf) '
           u'format("truetype");font-style:oblique 11deg}')
css.append(u'@font-face{font-family:SelObl;src:url(fonts/selawk.ttf) '
           u'format("truetype");font-style:oblique 11deg}')
css.append(u"""
:root{
  --reg:SegReg,SegSym,SelReg,"Helvetica Neue",sans-serif;
  --bold:SegBoldE,SegBoldD,SegBoldJ,SegBoldG,SegBoldH,SegSym,SelBold,"Helvetica Neue",sans-serif;
  --ital:SegItal,SegObl,SegSym,SelObl,"Helvetica Neue",sans-serif;
  --semi:SegSemiK,SegSemiA,SelSemi,SegBoldE,SegBoldD,SegSym,"Helvetica Neue",sans-serif;
  --black:SegBlack,SelBold,SegBoldE,SegBoldD,"Helvetica Neue",sans-serif;
  --mono:Menlo,monospace;
}
i,em,.ital{font-family:var(--ital);font-style:normal}
""")
io.open('fonts.css', 'w', encoding='utf-8').write(u'\n'.join(css) + u'\n')
print('wrote fonts.css  faces=%d' % len(faces))
for alias, name, cps in faces:
    print('  %-12s %-36s %d codepoints' % (alias, name, len(cps)))
